[tool.black]
line-length = 100
target-version = ['py38']  # Ajustez selon votre version Python
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
profile = "black"  # Assure la compatibilité avec Black
line_length = 100
skip_glob = "*/migrations/*"
known_django = "django"
sections = "FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
